In [18]:
#import libraries
!pip install kaggle
!pip install kagglehub

import kagglehub

# Download latest version
path = kagglehub.dataset_download("ankitbansal06/retail-orders")

print("Path to dataset files:", path)

Requirement already satisfied: kaggle in c:\users\monkh\anaconda3\lib\site-packages (1.7.4.5)
Requirement already satisfied: bleach in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (3.3.2)
Requirement already satisfied: idna in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (3.7)
Requirement already satisfied: protobuf in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (4.25.3)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (75.1.0)
Requirement already satisfied: six>=1.10 in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: text-unidecode in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (4.66.5)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (2.2.3)
Requirement already satisfied: webencodings in c:\users\monkh\anaconda3\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: packaging in c:\users\monkh\anaconda3\lib\site-packages (from bleach->kaggle) (24.1)
Requirement already satisfied: colorama in c:\users\monkh\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Collecting kagglehub
  Downloading kagglehub-0.3.13-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: packaging in c:\users\monkh\anaconda3\lib\site-packages (from kagglehub) (24.1)
Requirement already satisfied: pyyaml in c:\users\monkh\anaconda3\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\monkh\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\monkh\anaconda3\lib\site-packages (from kagglehub) (4.66.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\monkh\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\monkh\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\monkh\anaconda3\lib\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\monkh\anaconda3\lib\site-packages (from requests->kagglehub) (2025.1.31)
Requirement already satisfied: colorama in c:\users\monkh\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-0.3.13-py3-none-any.whl (68 kB)
Installing collected packages: kagglehub
Successfully installed kagglehub-0.3.13
Downloading from https://www.kaggle.com/api/v1/datasets/download/ankitbansal06/retail-orders?dataset_version_number=4...

100%|██████████| 200k/200k [00:00<00:00, 272kB/s]

Extracting files...
Path to dataset files: C:\Users\monkh\.cache\kagglehub\datasets\ankitbansal06\retail-orders\versions\4

In [3]:
    import os
    print(os.getcwd())

C:\Users\monkh

In [5]:
# #extract file from zip file
# import zipfile
# zip_ref = zipfile.ZipFile('orders.csv.zip') 
# zip_ref.extractall() # extract file to dir
# zip_ref.close() # close file

FileNotFoundError: [Errno 2] No such file or directory: 'orders.csv.zip'

In [22]:
#read data from the file and handle null values
import pandas as pd
    
df = pd.read_csv(r'C:\Users\monkh\.cache\kagglehub\datasets\ankitbansal06\retail-orders\versions\4\orders.csv',na_values=['Not Available','unknown'])

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [46]:
#rename columns names ..make them lower case and replace space with underscore
# df = df.rename(columns={'Order Id':'order_id', 'City':'city'})
# df.columns=df.columns.str.lower()
# df.columns=df.columns.str.replace(' ','_')
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [60]:
#derive new columns discount , sale price and profit
# df['discount']=df['list_price']*df['discount_percent']*.01
# df['sale_price']= df['list_price']-df['discount']
# df['profit']=df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [76]:
#convert order date from object data type to datetime
# df.dtypes
# pd.to_datetime(df['order_date'])
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [90]:
#drop cost price list price and discount percent columns
df = df.drop(columns=['list_price', 'cost_price','discount_percent'])
# df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

KeyError: "['list_price', 'cost_price', 'discount_percent'] not found in axis"

In [96]:
#load the data into sql server using replace option
# import sqlalchemy as sal
# # engine = sal.create_engine('mssql://ANKIT\SQLEXPRESS/master?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
# engine = sal.create_engine(
#     "mssql+pyodbc://MKDELL\\monkh@localhost/MSSQLSERVER02/RetailOrders?driver=ODBC+Driver+18+for+SQL+Server"
# )
# conn=engine.connect()

import urllib
import sqlalchemy as sal

params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=localhost\\MSSQLSERVER02;"
    "DATABASE=RetailOrders;"
    "Trusted_Connection=yes;"
    "Encrypt=no;"
)
engine = sal.create_engine(f"mssql+pyodbc:///?odbc_connect={params}")
conn = engine.connect()

In [100]:
#load the data into sql server using append option
df.to_sql('df_orders', con=conn , index=False, if_exists = 'append')

38